version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    ports:
      - '5433:5433'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -p 5433

volumes:
  postgres_data:
#
