/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface RefreshTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  userId: number;
  value: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface DB {
  refreshTokens: RefreshTokens;
  users: Users;
}
